### ISSUE TITLE
Poland

### ISSUE THREAD

**Issue by Redo11** [fergusch/media-literacy#1]
I love this idea and nobody really seems to care right now, so what about some polish cooperation? Like I will give some sites, translation etc.
I see no Poland mentioned, so I think it's an issue.

**Comment by fergusch** [comment]
Hi! It would be great to have some Polish websites, but I can only add sites that are featured on [mediabiasfactcheck.com](mediabiasfactcheck.com). Check out the [new websites](https://github.com/fergusch/media-literacy#new-websites) section of the README for some more info.
